[package]
name = "template"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "template"
path = "src/template.rs"

[features]
libtests = []

[dev-dependencies]
rand = "0.8.3"

[profile.test]
opt-level = 3
overflow-checks = true

[profile.release]
overflow-checks = true
